# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b246b03a61b003e9f2f097f8011bb620035ae299f1c66abc56b566596e7fd04817ed88573c4fddf19db9b157469a79e451631eaa6e0096a14609e8afe1e3488e

test:
  secret_key_base: 5bc05cd4f03ec814639d472d426a4f77d6fe4d6575c1fe6d5b3e8740c0b7d67285fa9405568aefffe605cde93cfca4d588ed19c10ae3f208c38ece34ec5dabde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
